# Generated by Django 5.2.8 on 2025-12-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_service_servicedocument_service_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='file',
            field=models.FileField(upload_to='service_documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
