# Generated by Django 5.2.8 on 2025-12-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicedocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
